@Library("dsd-jenkins-k8s") _

deployProject (
    serviceName: "sonar-java-demo",
    projectType: "maven",
    buildCommand: "mvn clean package -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080 -DskipTests=true",
    testCommand: "mvn test -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080",
	sonarCommand: "mvn sonar:sonar -DproxySet=true -Dhttps.proxyHost=pkg.proxy.prod.jp.local -Dhttps.proxyPort=10080",
    sonarQubeName: "SonarQubeDemo",
    skipDockerBuild: "true",
	skipDockerPush: "true",
    skipDeployment: "true",
    ignoreGitHeadMove: "true",
    targetEnv: "stg"
    )